// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StarWarsServiceClient is the client API for StarWarsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarWarsServiceClient interface {
	ConsultPlanet(ctx context.Context, in *ConsultRequest, opts ...grpc.CallOption) (*ConsultReply, error)
	SendInformationB(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error)
	SendInformationF(ctx context.Context, in *SendRequest2, opts ...grpc.CallOption) (*SendReply2, error)
}

type starWarsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarWarsServiceClient(cc grpc.ClientConnInterface) StarWarsServiceClient {
	return &starWarsServiceClient{cc}
}

func (c *starWarsServiceClient) ConsultPlanet(ctx context.Context, in *ConsultRequest, opts ...grpc.CallOption) (*ConsultReply, error) {
	out := new(ConsultReply)
	err := c.cc.Invoke(ctx, "/grpc.StarWarsService/ConsultPlanet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starWarsServiceClient) SendInformationB(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/grpc.StarWarsService/SendInformationB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starWarsServiceClient) SendInformationF(ctx context.Context, in *SendRequest2, opts ...grpc.CallOption) (*SendReply2, error) {
	out := new(SendReply2)
	err := c.cc.Invoke(ctx, "/grpc.StarWarsService/SendInformationF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarWarsServiceServer is the server API for StarWarsService service.
// All implementations must embed UnimplementedStarWarsServiceServer
// for forward compatibility
type StarWarsServiceServer interface {
	ConsultPlanet(context.Context, *ConsultRequest) (*ConsultReply, error)
	SendInformationB(context.Context, *SendRequest) (*SendReply, error)
	SendInformationF(context.Context, *SendRequest2) (*SendReply2, error)
	mustEmbedUnimplementedStarWarsServiceServer()
}

// UnimplementedStarWarsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStarWarsServiceServer struct {
}

func (UnimplementedStarWarsServiceServer) ConsultPlanet(context.Context, *ConsultRequest) (*ConsultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultPlanet not implemented")
}
func (UnimplementedStarWarsServiceServer) SendInformationB(context.Context, *SendRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInformationB not implemented")
}
func (UnimplementedStarWarsServiceServer) SendInformationF(context.Context, *SendRequest2) (*SendReply2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInformationF not implemented")
}
func (UnimplementedStarWarsServiceServer) mustEmbedUnimplementedStarWarsServiceServer() {}

// UnsafeStarWarsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarWarsServiceServer will
// result in compilation errors.
type UnsafeStarWarsServiceServer interface {
	mustEmbedUnimplementedStarWarsServiceServer()
}

func RegisterStarWarsServiceServer(s grpc.ServiceRegistrar, srv StarWarsServiceServer) {
	s.RegisterService(&StarWarsService_ServiceDesc, srv)
}

func _StarWarsService_ConsultPlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarWarsServiceServer).ConsultPlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StarWarsService/ConsultPlanet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarWarsServiceServer).ConsultPlanet(ctx, req.(*ConsultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarWarsService_SendInformationB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarWarsServiceServer).SendInformationB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StarWarsService/SendInformationB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarWarsServiceServer).SendInformationB(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarWarsService_SendInformationF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarWarsServiceServer).SendInformationF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StarWarsService/SendInformationF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarWarsServiceServer).SendInformationF(ctx, req.(*SendRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

// StarWarsService_ServiceDesc is the grpc.ServiceDesc for StarWarsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarWarsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.StarWarsService",
	HandlerType: (*StarWarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultPlanet",
			Handler:    _StarWarsService_ConsultPlanet_Handler,
		},
		{
			MethodName: "SendInformationB",
			Handler:    _StarWarsService_SendInformationB_Handler,
		},
		{
			MethodName: "SendInformationF",
			Handler:    _StarWarsService_SendInformationF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/StarWars.proto",
}
