// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/StarWars.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendIp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip1 string `protobuf:"bytes,1,opt,name=ip1,proto3" json:"ip1,omitempty"`
	Ip2 string `protobuf:"bytes,2,opt,name=ip2,proto3" json:"ip2,omitempty"`
}

func (x *SendIp) Reset() {
	*x = SendIp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendIp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIp) ProtoMessage() {}

func (x *SendIp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIp.ProtoReflect.Descriptor instead.
func (*SendIp) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{0}
}

func (x *SendIp) GetIp1() string {
	if x != nil {
		return x.Ip1
	}
	return ""
}

func (x *SendIp) GetIp2() string {
	if x != nil {
		return x.Ip2
	}
	return ""
}

type IpRecieve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IpRecieve) Reset() {
	*x = IpRecieve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpRecieve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRecieve) ProtoMessage() {}

func (x *IpRecieve) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRecieve.ProtoReflect.Descriptor instead.
func (*IpRecieve) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{1}
}

func (x *IpRecieve) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Planet  string `protobuf:"bytes,2,opt,name=planet,proto3" json:"planet,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *ConsultRequest) Reset() {
	*x = ConsultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultRequest) ProtoMessage() {}

func (x *ConsultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultRequest.ProtoReflect.Descriptor instead.
func (*ConsultRequest) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{2}
}

func (x *ConsultRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ConsultRequest) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *ConsultRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type ConsultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rebelds string `protobuf:"bytes,1,opt,name=rebelds,proto3" json:"rebelds,omitempty"`
	Clock   string `protobuf:"bytes,2,opt,name=clock,proto3" json:"clock,omitempty"`
}

func (x *ConsultReply) Reset() {
	*x = ConsultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultReply) ProtoMessage() {}

func (x *ConsultReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultReply.ProtoReflect.Descriptor instead.
func (*ConsultReply) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultReply) GetRebelds() string {
	if x != nil {
		return x.Rebelds
	}
	return ""
}

func (x *ConsultReply) GetClock() string {
	if x != nil {
		return x.Clock
	}
	return ""
}

type SendRequestB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Planet  string `protobuf:"bytes,2,opt,name=planet,proto3" json:"planet,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Value   string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SendRequestB) Reset() {
	*x = SendRequestB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequestB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestB) ProtoMessage() {}

func (x *SendRequestB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestB.ProtoReflect.Descriptor instead.
func (*SendRequestB) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{4}
}

func (x *SendRequestB) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SendRequestB) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *SendRequestB) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SendRequestB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SendRequestF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Planet  string `protobuf:"bytes,2,opt,name=planet,proto3" json:"planet,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Value   string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Fulcrum string `protobuf:"bytes,5,opt,name=fulcrum,proto3" json:"fulcrum,omitempty"`
}

func (x *SendRequestF) Reset() {
	*x = SendRequestF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequestF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestF) ProtoMessage() {}

func (x *SendRequestF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestF.ProtoReflect.Descriptor instead.
func (*SendRequestF) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{5}
}

func (x *SendRequestF) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SendRequestF) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *SendRequestF) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SendRequestF) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SendRequestF) GetFulcrum() string {
	if x != nil {
		return x.Fulcrum
	}
	return ""
}

type SendReplyB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port    string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Fulcrum string `protobuf:"bytes,3,opt,name=fulcrum,proto3" json:"fulcrum,omitempty"`
}

func (x *SendReplyB) Reset() {
	*x = SendReplyB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReplyB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplyB) ProtoMessage() {}

func (x *SendReplyB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplyB.ProtoReflect.Descriptor instead.
func (*SendReplyB) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{6}
}

func (x *SendReplyB) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SendReplyB) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *SendReplyB) GetFulcrum() string {
	if x != nil {
		return x.Fulcrum
	}
	return ""
}

type SendReplyF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clock string `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
}

func (x *SendReplyF) Reset() {
	*x = SendReplyF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_StarWars_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReplyF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplyF) ProtoMessage() {}

func (x *SendReplyF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_StarWars_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplyF.ProtoReflect.Descriptor instead.
func (*SendReplyF) Descriptor() ([]byte, []int) {
	return file_proto_StarWars_proto_rawDescGZIP(), []int{7}
}

func (x *SendReplyF) GetClock() string {
	if x != nil {
		return x.Clock
	}
	return ""
}

var File_proto_StarWars_proto protoreflect.FileDescriptor

var file_proto_StarWars_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x74, 0x61, 0x72, 0x57, 0x61, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2c, 0x0a, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x49, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x32, 0x22, 0x25, 0x0a, 0x09, 0x49, 0x70,
	0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x56, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x62,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x62, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x6a, 0x0a, 0x0c, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x22, 0x4a, 0x0a, 0x0a,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x32, 0xf3, 0x01, 0x0a,
	0x0f, 0x53, 0x74, 0x61, 0x72, 0x57, 0x61, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x10, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x10, 0x53, 0x65, 0x6e,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x12, 0x12, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x46, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x46, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x70, 0x1a,
	0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x70, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65,
	0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x61, 0x62, 0x69, 0x75, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x53, 0x74, 0x61, 0x72,
	0x57, 0x61, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_StarWars_proto_rawDescOnce sync.Once
	file_proto_StarWars_proto_rawDescData = file_proto_StarWars_proto_rawDesc
)

func file_proto_StarWars_proto_rawDescGZIP() []byte {
	file_proto_StarWars_proto_rawDescOnce.Do(func() {
		file_proto_StarWars_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_StarWars_proto_rawDescData)
	})
	return file_proto_StarWars_proto_rawDescData
}

var file_proto_StarWars_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_StarWars_proto_goTypes = []interface{}{
	(*SendIp)(nil),         // 0: grpc.SendIp
	(*IpRecieve)(nil),      // 1: grpc.IpRecieve
	(*ConsultRequest)(nil), // 2: grpc.ConsultRequest
	(*ConsultReply)(nil),   // 3: grpc.ConsultReply
	(*SendRequestB)(nil),   // 4: grpc.SendRequestB
	(*SendRequestF)(nil),   // 5: grpc.SendRequestF
	(*SendReplyB)(nil),     // 6: grpc.SendReplyB
	(*SendReplyF)(nil),     // 7: grpc.SendReplyF
}
var file_proto_StarWars_proto_depIdxs = []int32{
	2, // 0: grpc.StarWarsService.ConsultPlanet:input_type -> grpc.ConsultRequest
	4, // 1: grpc.StarWarsService.SendInformationB:input_type -> grpc.SendRequestB
	5, // 2: grpc.StarWarsService.SendInformationF:input_type -> grpc.SendRequestF
	0, // 3: grpc.StarWarsService.Identify:input_type -> grpc.SendIp
	3, // 4: grpc.StarWarsService.ConsultPlanet:output_type -> grpc.ConsultReply
	6, // 5: grpc.StarWarsService.SendInformationB:output_type -> grpc.SendReplyB
	7, // 6: grpc.StarWarsService.SendInformationF:output_type -> grpc.SendReplyF
	1, // 7: grpc.StarWarsService.Identify:output_type -> grpc.IpRecieve
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_StarWars_proto_init() }
func file_proto_StarWars_proto_init() {
	if File_proto_StarWars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_StarWars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendIp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpRecieve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequestB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequestF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReplyB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_StarWars_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReplyF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_StarWars_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_StarWars_proto_goTypes,
		DependencyIndexes: file_proto_StarWars_proto_depIdxs,
		MessageInfos:      file_proto_StarWars_proto_msgTypes,
	}.Build()
	File_proto_StarWars_proto = out.File
	file_proto_StarWars_proto_rawDesc = nil
	file_proto_StarWars_proto_goTypes = nil
	file_proto_StarWars_proto_depIdxs = nil
}
